theme: alembic-jekyll-theme

navigation_header:

- title: Home

  url: /

- title: Elements

  url: /elements/

- title: Blog

  url: /blog/

- title: Categories

  url: /categories/

- title: Search

  url: /search/

- title: Fork Alembic

  url: https://github.com/daviddarnes/alembic
